<a href="https://colab.research.google.com/github/heisenberg304/aprendiendo-ml-cloud/blob/semana-5/dia2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
#librerias
import pandas as pd

#importar dataset
data = pd.read_csv("/content/drive/MyDrive/data_csv/titanic.csv")

#Ver y analizar datos
surpervivientes = data["Pclass"].value_counts() #para saber que cantidad de valores hay en cada clase de la variable, funciona con todos

#Crear un subconjunto de:
#mujeres en primera clase
mujeres_1class = data[(data["Sex"] == "female") & (data["Pclass"] == 1)]

#Crear un subconjunto de:
#personas mayores de X con tarifa altadata.loc[(data["Age"]> 55) & (data["Fare"] > 25)]
data.loc[(data["Age"]> 55) & (data["Fare"] > 25)]

#Mostrar solo 2 columnas relevantes de ese subconjunto
mujeres_1class[["Age", "Pclass"]]
#Explicar qué estás intentando observar

#Usar groupby: df.groupby("columna")["otra_columna"].operación()
genero = data.groupby(["Sex"])["Survived"].mean()
clases = data.groupby(["Pclass"])["Survived"].mean()
classes.describe()

count    2.000000
mean     0.465473
std      0.391122
min      0.188908
25%      0.327191
50%      0.465473
75%      0.603756
max      0.742038
Name: Survived, dtype: float64

In [5]:
#librerias
import pandas as pd

#importar dataset
data = pd.read_csv("/content/drive/MyDrive/data_csv/titanic.csv")

#nuevas clases:
infantes = data[data["Age"] < 12]
infantes

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S
193,194,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,F2,S
237,238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,26.2500,NaN,S
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
340,341,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,F2,S
407,408,1,2,"Richards, Master. William Rowe",male,3.00,1,1,29106,18.7500,NaN,S
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S
530,531,1,2,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,26.0000,NaN,S
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,26.2500,NaN,S
549,550,1,2,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,36.7500,NaN,S
618,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,F4,S
720,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,248727,33.0000,NaN,S
750,751,1,2,"Wells, Miss. Joan",female,4.00,1,1,29103,23.0000,NaN,S
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
827,828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,NaN,C
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S