<a href="https://colab.research.google.com/github/heisenberg304/aprendiendo-ml-cloud/blob/semana-5/dia2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#librerias
import pandas as pd

#importar dataset
data = pd.read_csv("/content/drive/MyDrive/data_csv/titanic.csv")

#Ver y analizar datos
surpervivientes = data["Pclass"].value_counts() #para saber que cantidad de valores hay en cada clase de la variable, funciona con todos

#Crear un subconjunto de:
#mujeres en primera clase
mujeres_1class = data[(data["Sex"] == "female") & (data["Pclass"] == 1)]

#Crear un subconjunto de:
#personas mayores de X con tarifa altadata.loc[(data["Age"]> 55) & (data["Fare"] > 25)]
data.loc[(data["Age"]> 55) & (data["Fare"] > 25)]

#Mostrar solo 2 columnas relevantes de ese subconjunto
mujeres_1class[["Age", "Pclass"]]
#Explicar qué estás intentando observar

#Usar groupby: df.groupby("columna")["otra_columna"].operación()
genero = data.groupby(["Sex"])["Survived"].mean()
clases = data.groupby(["Pclass"])["Survived"].mean()
sex_Pclass = data.groupby(["Sex", "Pclass"])["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [8]:
#librerias
import pandas as pd

#importar dataset
data = pd.read_csv("/content/drive/MyDrive/data_csv/titanic.csv")

#limpieza de datos
data["Age"].fillna(data["Age"].median(), inplace=True)
data["Embarked"].fillna(data["Embarked"].mode()[0], inplace=True)
data = data.drop(["Cabin", "Name", "Ticket", "PassengerId"], axis=1)

#Transformaciones
data["Is_female"] = data["Sex"].map({"male": 0, "female":1})
data = data.drop("Sex", axis=1)
#Encoding
embarked = pd.get_dummies(data["Embarked"])
#unir al dataset
data = pd.concat([data, embarked], axis=1)

#comprobar:
data.isnull().sum()
data.head(10)

/tmp/ipykernel_1627/1146115980.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(data["Age"].median(), inplace=True)
/tmp/ipykernel_1627/1146115980.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Embarked"].fillna(data["Embarked"].mode()[0], inplace=True)

,Survived,Pclass,Age,SibSp,Parch,Fare,Embarked,Is_female,C,Q,S
0,0,3,22.0,1,0,7.2500,S,0,False,False,True
1,1,1,38.0,1,0,71.2833,C,1,True,False,False
2,1,3,26.0,0,0,7.9250,S,1,False,False,True
3,1,1,35.0,1,0,53.1000,S,1,False,False,True
4,0,3,35.0,0,0,8.0500,S,0,False,False,True
5,0,3,28.0,0,0,8.4583,Q,0,False,True,False
6,0,1,54.0,0,0,51.8625,S,0,False,False,True
7,0,3,2.0,3,1,21.0750,S,0,False,False,True
8,1,3,27.0,0,2,11.1333,S,1,False,False,True
9,1,2,14.0,1,0,30.0708,C,1,True,False,False