<a href="https://colab.research.google.com/github/heisenberg304/aprendiendo-ml-cloud/blob/semana-5/dia2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#librerias
import pandas as pd

#importar dataset
data = pd.read_csv("/content/drive/MyDrive/data_csv/titanic.csv")

#Ver y analizar datos
surpervivientes = data["Pclass"].value_counts() #para saber que cantidad de valores hay en cada clase de la variable, funciona con todos

#Crear un subconjunto de:
#mujeres en primera clase
mujeres_1class = data[(data["Sex"] == "female") & (data["Pclass"] == 1)]

#Crear un subconjunto de:
#personas mayores de X con tarifa altadata.loc[(data["Age"]> 55) & (data["Fare"] > 25)]
data.loc[(data["Age"]> 55) & (data["Fare"] > 25)]

#Mostrar solo 2 columnas relevantes de ese subconjunto
mujeres_1class[["Age", "Pclass"]]
#Explicar qué estás intentando observar

#Usar groupby: df.groupby("columna")["otra_columna"].operación()
genero = data.groupby(["Sex"])["Survived"].mean()
clases = data.groupby(["Pclass"])["Survived"].mean()
sex_Pclass = data.groupby(["Sex", "Pclass"])["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [13]:
#librerias
import pandas as pd

#importar dataset
data = pd.read_csv("/content/drive/MyDrive/data_csv/titanic.csv")

#limpieza de datos
data["Age"].fillna(data["Age"].median(), inplace=True)
data["Embarked"].fillna(data["Embarked"].mode()[0], inplace=True)
data = data.drop(["Cabin", "Name", "Ticket", "PassengerId"], axis=1)

#Transformaciones
data["Is_female"] = data["Sex"].map({"male": 0, "female":1})
data = data.drop("Sex", axis=1)

data["Relatives"] = data["SibSp"] + data["Parch"]
#Encoding
embarked = pd.get_dummies(data["Embarked"])
data = data.drop("Embarked", axis=1)
#unir al dataset
data = pd.concat([data, embarked], axis=1)

#comprobar:
data.isnull().sum()
data.head(10)

/tmp/ipykernel_1627/664399434.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(data["Age"].median(), inplace=True)
/tmp/ipykernel_1627/664399434.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Embarked"].fillna(data["Embarked"].mode()[0], inplace=True)

,Survived,Pclass,Age,SibSp,Parch,Fare,Is_female,Relatives,C,Q,S
0,0,3,22.0,1,0,7.2500,0,1,False,False,True
1,1,1,38.0,1,0,71.2833,1,1,True,False,False
2,1,3,26.0,0,0,7.9250,1,0,False,False,True
3,1,1,35.0,1,0,53.1000,1,1,False,False,True
4,0,3,35.0,0,0,8.0500,0,0,False,False,True
5,0,3,28.0,0,0,8.4583,0,0,False,True,False
6,0,1,54.0,0,0,51.8625,0,0,False,False,True
7,0,3,2.0,3,1,21.0750,0,4,False,False,True
8,1,3,27.0,0,2,11.1333,1,2,False,False,True
9,1,2,14.0,1,0,30.0708,1,1,True,False,False

MEJORANDO MODELOS ANTIGUOS:

In [14]:

#importar librerias
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
import pandas as pd

#CARGAR DATOS
data = pd.read_csv("/content/drive/MyDrive/data_csv/titanic.csv")



#Aplicar mediana para rellenar
data["Age"].fillna(data["Age"].median(), inplace=True)

#limpieza de datos
data["Age"].fillna(data["Age"].median(), inplace=True)
data["Embarked"].fillna(data["Embarked"].mode()[0], inplace=True)
data = data.drop(["Cabin", "Name", "Ticket", "PassengerId"], axis=1)

#Transformaciones
data["Is_female"] = data["Sex"].map({"male": 0, "female":1})
data = data.drop("Sex", axis=1)

data["Relatives"] = data["SibSp"] + data["Parch"]
#Encoding
embarked = pd.get_dummies(data["Embarked"])
data = data.drop("Embarked", axis=1)
#unir al dataset
data = pd.concat([data, embarked], axis=1)


#Separar x and y
x = data[["Pclass",	"Age",	"SibSp",	"Parch",	"Fare",	"Is_female",	"Relatives",	"C",	"Q",	"S"]]
y = data["Survived"]

#Separar dataset en train y test
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size = 0.2,
    random_state = 42
)

#crear modelo
model = DecisionTreeClassifier()
#entrenar el modelo
model.fit(x_train, y_train)
#testear modelo
pred = model.predict(x_test)

#metricas
matrix = confusion_matrix(y_test, pred)
accuracy = accuracy_score(y_test, pred)
precision = precision_score(y_test, pred)
recall = recall_score(y_test, pred)
f1 = f1_score(y_test, pred)

print(pred)
print(y_test)
print(f"matrix -> {matrix}")
print(f"accuracy -> {accuracy}")
print(f"precision -> {precision}")
print(f"recall -> {recall}")
print(f"f1 score -> {f1}")

[0 0 0 1 1 1 1 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1
 1 1 0 0 1 0 0 1 0 0 0 1 0 1 1 0 1 1 1 1 0 1 0 1 1 1 0 0 1 0 0 0 1 1 1 1 1
 0 0 1 1 1 1 0 1 1 0 0 0 1 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 1 1 0 1 1 1
 0 1 1 0 0 0 0 1 0 0 1 1 1 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1
 1 0 0 1 0 0 0 0 0 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1]
709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: Survived, Length: 179, dtype: int64
matrix -> [[84 21]
 [18 56]]
accuracy -> 0.7821229050279329
precision -> 0.7272727272727273
recall -> 0.7567567567567568
f1 score -> 0.7417218543046358

/tmp/ipykernel_1627/3558646894.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(data["Age"].median(), inplace=True)
/tmp/ipykernel_1627/3558646894.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(data["Age"].median(), inplace=True)
/tmp/ipykernel_1627/3558646894.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Embarked"].fillna(data["Embarked"].mode()[0], inplace=True)

In [15]:
#importar librerias
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
import pandas as pd

#CARGAR DATOS
data = pd.read_csv("/content/drive/MyDrive/data_csv/titanic.csv") #el csv quedo guardado en drive


#Aplicar mediana para rellenar
data["Age"].fillna(data["Age"].median(), inplace=True)

#limpieza de datos
data["Age"].fillna(data["Age"].median(), inplace=True)
data["Embarked"].fillna(data["Embarked"].mode()[0], inplace=True)
data = data.drop(["Cabin", "Name", "Ticket", "PassengerId"], axis=1)

#Transformaciones
data["Is_female"] = data["Sex"].map({"male": 0, "female":1})
data = data.drop("Sex", axis=1)

data["Relatives"] = data["SibSp"] + data["Parch"]
#Encoding
embarked = pd.get_dummies(data["Embarked"])
data = data.drop("Embarked", axis=1)
#unir al dataset
data = pd.concat([data, embarked], axis=1)


#Separar x and y
x = data[["Pclass",	"Age",	"SibSp",	"Parch",	"Fare",	"Is_female",	"Relatives",	"C",	"Q",	"S"]]
y = data["Survived"]


#Separar dataset en train y test
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size = 0.2,
    random_state = 42
)

#crear modelo
model = LogisticRegression()
#entrenar el modelo
model.fit(x_train, y_train)
#testear modelo
pred = model.predict(x_test)

#coeficientes e intercepto
w = model.coef_
b = model.intercept_

#metricas
matrix = confusion_matrix(y_test, pred)
accuracy = accuracy_score(y_test, pred)
precision = precision_score(y_test, pred)
recall = recall_score(y_test, pred)
f1 = f1_score(y_test, pred)

print(pred)
print(y_test)
print(f"coeficiente w = {w}, intercepto = {b}")
print(f"matrix -> {matrix}")
print(f"accuracy -> {accuracy}")
print(f"precision -> {precision}")
print(f"recall -> {recall}")
print(f"f1 score -> {f1}")
#print(x_train.shape) #(712, 5)
#print(x_test.shape)  #(179, 5)

[0 0 0 1 1 1 1 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 1 0 0 0
 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 1 1 1 0 1 1 0 0 1 0 0 0 1 1 1 1 1
 0 0 1 1 1 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1
 0 1 0 1 0 0 0 1 0 0 1 1 0 0 1 1 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 0 1 0 0
 1 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 1 0 0 1 1 0 1 0 0 0 1 1]
709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: Survived, Length: 179, dtype: int64
coeficiente w = [[-0.87360614 -0.02836107 -0.15874461  0.01820717  0.00282589  2.61413686
  -0.14053744  0.66113553  0.21935256  0.16406362]], intercepto = [1.15668558]
matrix -> [[90 15]
 [20 54]]
accuracy -> 0.8044692737430168
precision -> 0.782608695652174
recall -> 0.7297297297297297
f1 score -> 0.7552447552447552

/tmp/ipykernel_1627/1440130934.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(data["Age"].median(), inplace=True)
/tmp/ipykernel_1627/1440130934.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(data["Age"].median(), inplace=True)
/tmp/ipykernel_1627/1440130934.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Embarked"].fillna(data["Embarked"].mode()[0], inplace=True)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(